version: '3'
services:
    backend:
        build: ./backend
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/backend
    frontend:
        build: ./frontend
        volumes:
            - ./frontend:/frontend
